services:
  redis:
    image: redis:8.2 # use a specific version for stability
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 2s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "8001:8001"
    depends_on:
      - redis