// create table if not exists users(
// 	avatar varchar(400),
// 	id serial primary key,
//     firstName varchar(20) not null,
//     lastName varchar(20) not null,
//     email varchar(30) unique not null,
//     role enum("Employer", "Employee") default "Employee",
//     companyId serial not null,
//     phone int(10) not null,
//     date_of_birth date,
//     address varchar(80),
//     employeeId varchar(8),
//     department enum("EN", "HR", "MR", "SL", "FN", "OP") not null,
//     designation varchar(16) not null,
//     joiningDate date default now(),
//     managerAssigned varchar(40) not null,
//     isActive boolean default true,
//     isAdmin boolean default false,
//     basicSalary int not null,
//     hra int default 0,
//     da int default 0,
//     allowance int default 0,
//     deductions int default 0
// )